### ISSUE TITLE
m3u connection problem

### ISSUE THREAD

**Issue by SimonZhouxz** [efoxbr/megacubo#31] opened 2023-10-18 12:55 UTC
Hello, I use megacubo on Android phone and my Win11 PC. I can watch my m3u source smoothly on my phone. However I can barely connect to my source successfully on my PC under the same wifi environment, the same channel and the same configuration. 

I've tested it with direct m3u url as well as host with username and password, but it didn't work. It seems that my m3u source only supports mpegts. I wondered it had something to do about it but the source works on my phone.

Also, I tried record function, used it to record tv for 30 minutes. It recorded the whole 30 minutes successfully on PC. But on my android phone, the record video became a lot of patches , each of which has only 1 minute. Again, the record was under the same internet environment, same channel, and I tested it for 3 times.

Hope someone who met the same situation could share their expirence, or kind developers could solve these in future version.

**Comment by efoxbr** [comment] 2023-10-20 21:00
Hello @SimonZhouxz, could you check if this problem still happens with version 17.2.6?

**Comment by SimonZhouxz** [comment] 2023-10-21 15:26
> Hello @SimonZhouxz, could you check if this problem still happens with version 17.2.6?

I appreciate your enthusiasm. Unfortunately it didn't work. Logging with Xtream code on my PC, it costs about 5 hours to get my iptv list, which can be downloaded from edge browser in 3 minutes. And it can't connect to my iptv source with m3u url or Xtream code., which is accessible with IPTV Smarters pro. It just continue informing time out, even it shows test connect is successful with ts before.

![屏幕截图 2023-10-21 230147](https://github.com/efoxbr/megacubo/assets/71009679/855bf4f0-4acc-43d2-a7ad-4cba834c2d43)

On my android phone it took more less time to download m3u list successfully both with m3u url and Xtream code. But the record was still splited up in the new version.

![Screenshot_20231021-230444](https://github.com/efoxbr/megacubo/assets/71009679/4d088843-a993-4d7f-96b1-064d430c75d9)

Some of them was blocked by official source. 

Since it can't connect on PC, I can't test record on the PC platform. but it works smoothly on version 17.2.5. 

I wonder if it has something to do with my source, since my source only supports mpegts and on abroad. It just did not work for me. Thanks for your kind help again.

**Comment by efoxbr** [comment] 2023-12-06 00:13
@SimonZhouxz Due to the way Megacubo works (indexing the list locally) it works best with M3U lists, as they make all the content available at once. Using the Xtream protocol, many calls are needed to index the content, which makes it slow to add to the list.

The PC connection issue should be resolved in version 17.3.3 (if it is a connectivity issue). If it persists, it is possible that the codec used in the transmission is not supported in the computer version (based on Electron, we use a customized version of it to add HEVC support in the releases). In this case you can click on the "refresh" icon (two arrows in a circle) in the player controls and select "Open with external player" to use the player of your choice.

Regarding the problem with recordings, we were unable to reproduce the bug in the current version, if it still occurs please let us know.

https://github.com/efoxbr/megacubo/releases/latest

**Closed** 2023-12-06 00:34 UTC
