### ISSUE TITLE
Showing unexpected percentage when trying to load channels from m3u url.

### ISSUE THREAD

**Issue by mrdebugger007** [efoxbr/megacubo#22] opened 2023-01-24 20:34 UTC
![Screenshot_20230125-015714_Megacubo](https://user-images.githubusercontent.com/123509410/214402821-9f3697d4-3f4f-4e0e-904e-87a435583f1b.jpg)
-help needed

**Comment by efoxbr** [comment] 2023-01-26 23:50
@mrdebugger007 Thanks for pointing out this bug. Could you test again with version 16.8.1 from the link below to confirm that this bug is resolved?

https://github.com/efoxbr/megacubo/releases/v16.8.1

**Comment by mrdebugger007** [comment] 2023-01-27 05:41
> @mrdebugger007 Thanks for pointing out this bug. Could you test again with version 16.8.1 from the link below to confirm that this bug is resolved?
> 
> https://github.com/efoxbr/megacubo/releases/v16.8.1

The issue with the percentage has been resolved, however, it has caused two new issues to arise. Firstly, the loading process stops automatically after reaching around 65% or 67% is it the expected behavior? Secondly, the app is not responding properly when attempting to access a folder or click on any items, displaying a message but no action occurs.

This video shows what's happening:

https://youtube.com/shorts/qr7BrOMm5jo?feature=share

**Comment by efoxbr** [comment] 2023-01-28 16:24
> [...] the loading process stops automatically after reaching around 65% or 67% is it the expected behavior? 

Yes. The previous problem was caused by the missing Content-Length header in the response, so the program couldn't calculate and display any progress.

So, for these cases, I hardcoded a dummy size corresponding to a large list (100MB) to display progress (even if inconsistent) to the user, which seemed less tedious and frustrating for the user.

As a side effect, the download of the list may finish before 100%, if the list is smaller than the estimated size, or stay at 99% for a long time at the end if the list is much larger.

https://github.com/efoxbr/megacubo/blob/b85dd91b2c42d13737508c91027e9e71defe94d5/www/nodejs-project/modules/lists/update-list-index.js#L250

> [...] Secondly, the app is not responding properly when attempting to access a folder or click on any items, displaying a message but no action occurs.

That was a silly logic error that somehow got unnoticed in the commit. Sorry about that.

https://github.com/efoxbr/megacubo/blob/b85dd91b2c42d13737508c91027e9e71defe94d5/www/nodejs-project/modules/streamer/streamer.js#L170

This bug was fixed in [commit v16.8.1-rev2](https://github.com/efoxbr/megacubo/commit/5d680ae5884d77ee3def1f2accc3b131cdfb534c) and installers were updated in the pre-release below.

https://github.com/efoxbr/megacubo/releases/tag/v16.8.1

**Comment by mrdebugger007** [comment] 2023-01-28 18:12
> > [...] the loading process stops automatically after reaching around 65% or 67% is it the expected behavior?
> 
> Yes. The previous problem was caused by the missing Content-Length header in the response, so the program couldn't calculate and display any progress.
> 
> So, for these cases, I hardcoded a dummy size corresponding to a large list (100MB) to display progress (even if inconsistent) to the user, which seemed less tedious and frustrating for the user.
> 
> As a side effect, the download of the list may finish before 100%, if the list is smaller than the estimated size, or stay at 99% for a long time at the end if the list is much larger.
> 
> https://github.com/efoxbr/megacubo/blob/b85dd91b2c42d13737508c91027e9e71defe94d5/www/nodejs-project/modules/lists/update-list-index.js#L250
> 
> > [...] Secondly, the app is not responding properly when attempting to access a folder or click on any items, displaying a message but no action occurs.
> 
> That was a silly logic error that somehow got unnoticed in the commit. Sorry about that.
> 
> https://github.com/efoxbr/megacubo/blob/b85dd91b2c42d13737508c91027e9e71defe94d5/www/nodejs-project/modules/streamer/streamer.js#L170
> 
> This bug was fixed in [commit v16.8.1-rev2](https://github.com/efoxbr/megacubo/commit/5d680ae5884d77ee3def1f2accc3b131cdfb534c) and installers were updated in the pre-release below.
> 
> https://github.com/efoxbr/megacubo/releases/tag/v16.8.1

When attempting to load an m3u file using a URL, the loading percentage reaches 67% and then resets back to 0%, causing the list to reload multiple times. 

Video: https://youtu.be/enEvpDKLPOI

Additionally, even after successfully loading the list multiple times, some channels do not play correctly and either display an error message about a broadcaster issue or a black screen. However, when attempting to play the same channels on a different app, they work without issue.

The video is set to play at 2.5x speed.
Video: https://youtu.be/mivKbLFELQ4

Ps: After loading lists app size is going over 1GB.

**Comment by efoxbr** [comment] 2023-02-08 00:48
@mrdebugger007 Could you test again with version 16.8.4 please?

**Comment by mrdebugger007** [comment] 2023-02-09 17:21
> @mrdebugger007 Could you test again with version 16.8.4 please?

Still same issue.

**Comment by efoxbr** [comment] 2023-07-28 22:51
@mrdebugger007 The issue is resolved in the current version. If you notice any other problems please let me know.

**Closed by efoxbr** 2023-07-28 22:51 UTC
Labels: bug
